DROP TABLE SINGROOM;



DROP TABLE ROOM;



DROP TABLE RSV;



DROP TABLE user;


CREATE TABLE SINGROOM (
     STORE_ID     VARCHAR(10)     NOT NULL,
     STORE_NAME     VARCHAR(50)     NULL,
     RUN_YMD     VARCHAR(8)     NULL
);

CREATE UNIQUE INDEX SINGROOM_PK ON SINGROOM
(
     STORE_ID
);

ALTER TABLE SINGROOM
ADD PRIMARY KEY (STORE_ID);


CREATE TABLE ROOM (
     STORE_ID     VARCHAR(10)     NOT NULL,
     ROOM_NUM     NUMERIC(3)     NOT NULL,
     MAX_PER     NUMERIC(2)     NULL
);

CREATE UNIQUE INDEX ROOM_PK ON ROOM
(
     STORE_ID,
     ROOM_NUM
);

ALTER TABLE ROOM
ADD PRIMARY KEY (STORE_ID, ROOM_NUM);

CREATE TABLE RSV (
     STORE_ID     VARCHAR(10)     NOT NULL,
     ROOM_NUM     NUMERIC(3)     NOT NULL,
     USER_ID     VARCHAR(10)     NOT NULL,
     RSV_ID     VARCHAR(12)     NOT NULL,
     RSV_YMD     VARCHAR(8)     NULL,
     RSV_TIME     VARCHAR(4)     NULL,
     RSV_HOUR     NUMERIC(2)     NULL,
     FEE     NUMERIC(7)     NULL
);

CREATE UNIQUE INDEX RSV_PK ON RSV
(
     STORE_ID,
     ROOM_NUM,
     USER_ID,
     RSV_ID
);

ALTER TABLE RSV
ADD PRIMARY KEY (STORE_ID, ROOM_NUM, USER_ID, RSV_ID);

CREATE TABLE USER (
     USER_ID     VARCHAR(10)     NOT NULL,
     USER_NAME     VARCHAR(20)     NULL,
     USER_AGE     NUMERIC(3)     NULL,
     USER_PHONE     VARCHAR(20)     NULL
);


CREATE UNIQUE INDEX USER_PK ON USER
(
     USER_ID
);

ALTER TABLE USER
ADD PRIMARY KEY (USER_ID);

